apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: datadirdesa-mysql-0
    labels:
        app: mysqldesa
    annotations:
        volume.beta.kubernetes.io/storage-class: "any"
        volume.beta.kubernetes.io/mount-options: "uid=27,gid=27"
spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: datadirdesa-mysql-1
    labels:
        app: mysqldesa
    annotations:
        volume.beta.kubernetes.io/storage-class: "any"
        volume.beta.kubernetes.io/mount-options: "uid=27,gid=27"
spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: datadirdesa-mysql-2
    labels:
        app: mysqldesa
    annotations:
        volume.beta.kubernetes.io/storage-class: "any"
        volume.beta.kubernetes.io/mount-options: "uid=27,gid=27"
spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  #storageClassName: any
  #hostPath:
  #  path: /data/datadir-mysql-2/
