
apiVersion: v1
kind: Service
metadata:
  name: myadmin
  namespace: project-atp
  labels:
    app: mysql
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: myadmin
